/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueuesIdRouteImport } from './routes/queues.$id'
import { Route as QueuesAdminIdRouteImport } from './routes/queues-admin.$id'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesIdRoute = QueuesIdRouteImport.update({
  id: '/queues/$id',
  path: '/queues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesAdminIdRoute = QueuesAdminIdRouteImport.update({
  id: '/queues-admin/$id',
  path: '/queues-admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/teacher': typeof TeacherRoute
  '/queues-admin/$id': typeof QueuesAdminIdRoute
  '/queues/$id': typeof QueuesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/teacher': typeof TeacherRoute
  '/queues-admin/$id': typeof QueuesAdminIdRoute
  '/queues/$id': typeof QueuesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/teacher': typeof TeacherRoute
  '/queues-admin/$id': typeof QueuesAdminIdRoute
  '/queues/$id': typeof QueuesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy' | '/teacher' | '/queues-admin/$id' | '/queues/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/teacher' | '/queues-admin/$id' | '/queues/$id'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/teacher'
    | '/queues-admin/$id'
    | '/queues/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TeacherRoute: typeof TeacherRoute
  QueuesAdminIdRoute: typeof QueuesAdminIdRoute
  QueuesIdRoute: typeof QueuesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/$id': {
      id: '/queues/$id'
      path: '/queues/$id'
      fullPath: '/queues/$id'
      preLoaderRoute: typeof QueuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues-admin/$id': {
      id: '/queues-admin/$id'
      path: '/queues-admin/$id'
      fullPath: '/queues-admin/$id'
      preLoaderRoute: typeof QueuesAdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TeacherRoute: TeacherRoute,
  QueuesAdminIdRoute: QueuesAdminIdRoute,
  QueuesIdRoute: QueuesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
